apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-app-container
          image: nginx:stable
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: my-app-config
